.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/cla.yml
.github/workflows/test.yml
LICENSE
README.md
RELEASE.md
buildscripts/build.bat
buildscripts/build.sh
buildscripts/getFrogbot.sh
release/buildAndUpload.sh
release/pipelines.yml
release/specs/frogbot-rbc-spec.json

* Add release automation
* Add CI tests
* Add CLA assistant
* Add pull requests and issues templates
* Add readme template
* Add license

Add repository basics

---

commands/scanpullrequest_test.go
commands/utils/icons.go
commands/utils/icons_test.go

Fix severity icons issue

---

README.md
commands/utils/consts.go
templates/github-actions/frogbot-npm.yml

Documentation + JF_INSTALL_DEPS_CMD

---

action/lib/utils.js
action/src/utils.ts
commands/scanpullrequest.go
commands/utils/params.go
main.go

Add '--use-labels' flag

---

commands/utils/consts.go
commands/utils/icons_test.go
commands/utils/params.go
commands/utils/params_test.go
commands/utils/utils.go

Improve error messages

---

README.md
templates/github-actions/README.md
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml

Update README and templates

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/testdata/messages/dummyvulnerabilities.md
commands/testdata/messages/novulnerabilities.md
commands/utils/consts.go

Expand Frogbot tests

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/utils/utils_test.go

Add more tests

---

.github/workflows/frogbot.yml
README.md
commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/utils/consts.go
commands/utils/icons.go
commands/utils/params.go
commands/utils/utils.go
main.go
templates/github-actions/frogbot-dotnet.yml
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml
templates/github-actions/frogbot-nuget.yml
templates/github-actions/frogbot-pip.yml
templates/github-actions/frogbot-pipenv.yml

Fix code review comments

---

README.md
templates/github-actions/README.md
templates/github-actions/frogbot-dotnet.yml
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml
templates/github-actions/frogbot-nuget.yml
templates/github-actions/frogbot-pip.yml
templates/github-actions/frogbot-pipenv.yml

---
* Removed the GitHub Actions structure from the README and left a link to the templates README only.
* Modified the structure of the README, so that it has better separation between the functionality and the installation of Frogbot.
* Added supported tools to the README.
* Removed the "Download Frogbot Manually" section. I think we can come with a better solution for it. 
* Enhanced the templates README to include all the information needed to use the templates.
* In all the templates that need the *JF_INSTALL_DEPS_CMD* variable, I put it as the first variable.
* Added to all templates the *JF_WATCHES* and *JF_PROJECT* commented out.

Docs update

---

README.md
templates/github-actions/README.md
templates/github-actions/frogbot-dotnet.yml
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml
templates/github-actions/frogbot-nuget.yml
templates/github-actions/frogbot-pip.yml
templates/github-actions/frogbot-pipenv.yml

---
* Typos fixes on the README
* Improvements to the GitHub Actions templates.

Docs fixes & improvements

---

.github/workflows/frogbot.yml
commands/utils/consts.go
commands/utils/params_test.go

Rename JF_TOKEN to  JF_ACCESS_TOKEN

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go

Fail the frogbot scan if the PR isn't label with the frogbot label

---

.github/workflows/test.yml

Automatically  un-label safe to test 

---

README.md

Add GitLab execution script on Windows

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go

Fail Frogbot if it hasn't been run yet

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/utils/consts.go
commands/utils/utils.go
commands/utils/utils_test.go

Send usage report

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go

Fix jfrog-cli-core changes

---

README.md

Add JF_GIT_API_ENDPOINT Variable

---

templates/github-actions/frogbot-dotnet.yml
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml
templates/github-actions/frogbot-nuget.yml
templates/github-actions/frogbot-pip.yml
templates/github-actions/frogbot-pipenv.yml

Add instructions for JF_GIT_API_ENDPOINT in GitHub

---

.github/workflows/test.yml

---
This PR adds a new sanity test to the Frogbot tests suite. The new test will build and run the current code of Frogbot (including all the changes introduced by each PR).
Please notice, that the frogbot.yml is not changed and will trigger the most recent published Frogbot action when the "Frogbot scan" label is added.
The 2 comments can then be compared for sanity.

New Frogobt sanity test

---

.github/workflows/frogbot.yml
README.md
commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/utils/consts.go
commands/utils/params.go
commands/utils/testsutils.go
commands/utils/utils.go
commands/utils/utils_test.go
main_test.go
templates/github-actions/README.md
templates/github-actions/frogbot-dotnet.yml
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-gradle.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml
templates/github-actions/frogbot-nuget.yml
templates/github-actions/frogbot-pip.yml
templates/github-actions/frogbot-pipenv.yml

Fix error handling and static analysis

---

README.md
commands/commands.go
commands/createfixpullrequests.go
commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/scanpullrequests.go
commands/utils/consts.go
commands/utils/icons.go
commands/utils/params.go
commands/utils/utils.go
templates/Jenkins/Jenkinsfile

Add Support for Bitbucket Server

---

commands/createfixpullrequests_test.go

Add VersionChange parsing test

---

README.md
templates/github-actions/frogbot-go.yml
templates/github-actions/frogbot-maven.yml
templates/github-actions/frogbot-npm.yml

yml template updates

---

commands/scanpullrequests.go

Fix Scan All Pull Requests

---

README.md
commands/utils/consts.go
commands/utils/params.go
commands/utils/params_test.go

Fix bitbucket server git provider name

---

README.md

Add Pipelines Example to README

---

.github/workflows/test.yml
README.md

Cleanup README

---

README.md

Fix .gitlab-ci.yml

---

README.md
commands/commands.go
commands/createfixpullrequests.go

---
This PR Fixs GitLab ci yml example and adds more informative log prints.

Fix to GitLab's documentation

---

commands/createfixpullrequests.go
commands/utils/git.go

Create PR Fixes in Temp Directory

---

commands/createfixpullrequests.go
commands/utils/git.go

Add missing authentication to remote.List method

---

.github/workflows/test.yml
go.mod
go.sum

Fix compilation

---

.github/workflows/test.yml

Update test.yml pip/pipenv install

---

README.md
commands/createfixpullrequests.go
commands/utils/utils.go

Fix Scan and Fix issue for Go + README edit

---

starter-workflows/code-scanning/frogbot-scan-and-fix.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml

---
security-events: write is missing for the scan and fix
depends on:
https://github.com/jfrog/froggit-go/pull/46

Fix Permission issue for sarif upload

---

go.mod
go.sum
starter-workflows/code-scanning/frogbot-scan-and-fix.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml

go.mod update

---

templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml

---
Following https://github.com/jfrog/frogbot/issues/145

Add JF_REQUIREMENTS_FILE env to pip scan yaml

---

starter-workflows/code-scanning/frogbot-scan-and-fix.yml
starter-workflows/code-scanning/frogbot-scan-pr.yml

Update starter-workflows yaml's

---

commands/scanpullrequest.go
commands/scanpullrequests.go
go.mod
go.sum

Improve logs and scan multiple PRs aggregate errors

---

README.md
commands/createfixpullrequests.go
commands/createfixpullrequests_test.go
commands/testdata/projects/poetry/poetry.lock
commands/testdata/projects/poetry/pyproject.toml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml

Add poetry support

---

.github/workflows/test.yml

Update Poetry tests

---

commands/testdata/projects/poetry/poetry.lock
commands/testdata/projects/poetry/pyproject.toml

Fix Poetry test

---

.github/workflows/analysis.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pr.yml
.github/workflows/test.yml
commands/utils/mavenutils.go
go.mod
starter-workflows/code-scanning/frogbot-scan-and-fix.yml
starter-workflows/code-scanning/frogbot-scan-pr.yml
templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml

Upgrade GO to 1.19.x

---

release/pipelines.yml

Change 'release_frogbot' Go version

---

commands/scanpullrequest.go
commands/scanpullrequests.go

Fix duplicate working dirs when with scan-pull-requests

---

commands/scanpullrequest.go
commands/scanpullrequests_test.go
commands/utils/icons.go
commands/utils/icons_test.go

Remove emojis from pull request comment in Bitbucket Server

---

commands/createfixpullrequests.go
commands/createfixpullrequests_test.go

Bug Fix - vulnerability fix version suggested downgrading the current version
---

Bug Fix - vulnerability fix version suggested downgrading the current version

---

commands/scanpullrequests_test.go

fix TestScanAllPullRequestsMultiRepo

---

.frogbot/frogbot-config.yml

Fix params tests

---

commands/scanpullrequest.go
commands/scanpullrequest_test.go
commands/utils/consts.go

Verify Environment on GitHub Actions

---

README.md
docs/install-azure-repos.md
docs/install-bitbucket-server.md
docs/install-github.md

---
Add notice for open-source projects.
https://github.com/yahavi/frogbot/tree/warn

Add notice for open-source projects

---

README.md
docs/frogbot-config.md
docs/install-azure-repos.md
docs/install-bitbucket-server.md
docs/install-github.md
docs/install-gitlab.md
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
starter-workflows/code-scanning/frogbot-scan-and-fix.yml
starter-workflows/code-scanning/frogbot-scan-pr.yml

---
Made the following changes in all the templates:
1. Moved the optional JF_USER and JF_PASSWORD variable to be right after the JF_ACCESS_TOKEN for better readability of the config.
2. Added JF_INSTALL_DEPS_CMD variable to all the templates, becuase it should be used, if the frogbot-config.yml file isn't used.
3. Update the "Creating the frogbot-config.yml file" section, to let the users know that the file isn't mandatory for all projects.
4. Added the creation of the frogbot-config.yml file to the README as an installation step. 
5. As a rsult of change 4 abiove, removed the creation of the frogbot-config.yml file from the installation pages of all the git providers.  
6. Added the JF_RELEASES_REPO, JF_DEPS_REPO and JF_INSTALL_DEPS_CMD to the starter-workflows templates.

Documentation changes

---

docs/frogbot-config.md

Documentation typo fix

---

.github/workflows/analysis.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pr.yml
.github/workflows/test.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
release/pipelines.yml

Update Frogbot's release, tests and templates to use Go 1.20.x

---

release/pipelines.yml

Fix release pipeline

---

release/pipelines.yml

Release automation - merge to dev

---

docs/frogbot-config.md
docs/templates/github-actions/README.md

Add notes to the documentation

---

README.md

---
Updating the PR scan table in the documentation, following the recent table layout changes.

Update PR scan table in the documentation

---

commands/createfixpullrequests.go

---
Fix bug that committed to master branch when branch already exists on remote.
return error instead.

Fix commit to master bug

---

commands/testdata/config/frogbot-config-clean-test-proj.yml
commands/testdata/config/frogbot-config-multi-dir-test-proj-no-fail.yml
commands/testdata/config/frogbot-config-multi-dir-test-proj.yml
commands/testdata/config/frogbot-config-scan-and-fix-repos.yml
commands/testdata/config/frogbot-config-test-params.yml
commands/testdata/config/frogbot-config-test-proj-no-fail.yml
commands/testdata/config/frogbot-config-test-proj-subdir.yml
commands/testdata/config/frogbot-config-test-proj.yml
commands/testdata/config/frogbot-config-test-unmarshal.yml
commands/utils/params_test.go
docs/frogbot-config.md
docs/install-azure-repos.md
docs/install-bitbucket-server.md
docs/install-github.md
docs/install-gitlab.md
docs/templates/.frogbot/frogbot-config.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
docs/templates/jfrog-pipelines/pipelines-dotnet.yml
docs/templates/jfrog-pipelines/pipelines-npm.yml
docs/templates/jfrog-pipelines/pipelines-pip.yml
docs/templates/jfrog-pipelines/pipelines-yarn2.yml
schema/frogbot-schema.json
starter-workflows/code-scanning/frogbot-scan-and-fix.yml
starter-workflows/code-scanning/frogbot-scan-pr.yml

---
Since it is no longer required to set the `JF_INSTALL_DEPS_CMD` or `installCommand` variable for npm, this PR updates the documentation and test accordingly.

Delete 'npm i' from the documentation and tests 

---

go.mod
go.sum

Upgrade froggit-go to v1.7.3, which includes bug fixes

---

docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
starter-workflows/code-scanning/frogbot-scan-and-fix.yml

Fix GitHub actions templates

---

go.mod
go.sum

---
The fix was implemented in https://github.com/jfrog/jfrog-cli-core/pull/808

Infinite loop while parsing Npm dependency list

---

commands/createfixpullrequests.go

Fix aggregated pull requests

---

commands/utils/packagehandlers/mavenpackagehandler.go

---
Should resolve the following issue:
> ERROR org.apache.maven.cli.MavenCli - No plugin found for prefix 'versions' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories

Specify coordinates of the Maven versions plugin

---

docs/install-gitlab.md

Update install-gitlab.md template

---

commands/createfixpullrequests_test.go

Improve git error logs on test

---

release/pipelines.yml

Fix release intergation

---

commands/createfixpullrequests_test.go
commands/utils/utils.go
commands/utils/utils_test.go
go.mod
go.sum

Improve GetUniqueID

---

commands/scanpullrequest.go
commands/utils/depsutil.go
commands/utils/depsutil_test.go
commands/utils/packagehandlers/commonpackagehandler.go
commands/utils/params.go
commands/utils/params_test.go

Rename resolver repository field to depsRepo to avoid confusion with Git repository

---

go.mod
schema/schemas_test.go

Remove redundant yaml.v2 dependency

---

commands/commands.go
commands/createfixpullrequests_test.go
commands/scanandfixrepos_test.go
commands/scanpullrequest_test.go
commands/scanpullrequests_test.go
commands/utils/git_test.go
commands/utils/params.go
commands/utils/params_test.go
commands/utils/utils.go

Improve internal field names

---

commands/createfixpullrequests_test.go
commands/scanpullrequest.go
commands/utils/params_test.go

Fix aggregate PRs test

---

.github/workflows/analysis.yml
.github/workflows/cla.yml
commands/scanpullrequest/scanallpullrequests_test.go
commands/scanpullrequest/scanpullrequest_test.go
commands/scanrepository/scanrepository_test.go
commands/utils/testsutils.go
go.mod
go.sum

Fix mock import

---

.github/workflows/test.yml
action/lib/utils.js
action/src/utils.ts

Remove base branch from github actions

---

.github/ISSUE_TEMPLATE/bug_report.yml
commands/scanrepository/scanmultiplerepositories.go
commands/scanrepository/scanrepository.go
commands/utils/scandetails.go

---
There was a checkout in an early stage before cloning the repository which caused an error when we only download the source code 
Fix: 
Move the checkout to target branch right after the clone operation.

Fix scan-and-fix-repos faulty checkout

---

release/buildAndUpload.sh

Remove 'main.go' from buildAndUpload.sh

---

.frogbot/frogbot-config.yml
.github/workflows/frogbot-scan-and-fix.yml
.github/workflows/frogbot-scan-pr.yml
go.mod
go.sum
scanpullrequest/scanpullrequest_test.go
scanrepository/scanmultiplerepositories_test.go
scanrepository/scanrepository.go
utils/git.go
utils/git_test.go

Add .git with remote details before clone if needed

---

.github/workflows/frogbot-scan-pr.yml

Fix Scan-Pull-Request workflow

---

utils/reviewcomment.go

Fix try to delete main comment at review

---

go.mod
go.sum
utils/outputwriter/outputwriter.go
utils/reviewcomment.go

Fix GitHub delete review comments

---

.github/workflows/validate-pr-target-branch.yml

Add validate-pr-target-branch.yml action

---

packagehandlers/mavenpackagehandler.go

---
Fixes:
https://github.com/jfrog/frogbot/issues/501

Download maven-install-plugin with JF_DEPS_REPO

---

utils/utils.go
utils/utils_test.go

Add error on usage when no repositories provided

---

schema/schemas_test.go

Fix download handler on schema tests

---

scanpullrequest/scanpullrequest.go
scanpullrequest/scanpullrequest_test.go

Add licenses to aggregateScanResults

---

packagehandlers/gradlepackagehandler.go
packagehandlers/packagehandlers_test.go

---
changed fixGradleVulnerability function into a handler's method

Gradle- changed handler's fix function into method

---

scanpullrequest/scanpullrequest.go
utils/comment.go

PR Scanning - Prevent Frogbot from failing when comment removal fails

---

release/buildAndUpload.sh

---
After changing module name we need to adjust the release script with v2

Fix version path in release

---

.github/workflows/test.yml

---
to Fix tests that have timeout on Windows sometimes.

Turn Gradle daemon off for tests

---

.github/workflows/analysis.yml
.github/workflows/test.yml
go.mod
go.sum

Update Go version to 1.21

---

testdata/messages/reviewcomment/review_comment_fallback_simplified.md
testdata/messages/reviewcomment/review_comment_fallback_standard.md
utils/outputwriter/outputcontent.go

Remove duplicated footer at fallback comments

---

.github/workflows/test.yml

Fixing Java version in test.yml to v11

---

commands.go
go.mod
go.sum
scanpullrequest/scanpullrequest.go
scanpullrequest/scanpullrequest_test.go
scanrepository/scanrepository.go
utils/analytics.go
utils/analytics_test.go
utils/outputwriter/outputcontent_test.go
utils/params.go
utils/scandetails.go
utils/utils.go
utils/utils_test.go

---
Depends on: https://github.com/jfrog/jfrog-cli-security/pull/93

Refactor after severity and utils changes in security-cli

---

go.mod
go.sum
utils/utils.go
utils/utils_test.go

---
Depends on: 
* https://github.com/jfrog/jfrog-cli-security/pull/138
Code to patch the results so it will be passed by Github rules was transferred to Security-CLI

Fix breaking changes after security PR

---

scanrepository/scanrepository.go

Upload result to GHAS only if JAS entitled

---

scanrepository/scanrepository.go

---
Remove redundant log about fixing issues in detection mode:

Remove "fix log" in detection only mode

---

go.mod
go.sum

update dependencies for release 2.23.0

---

go.mod
go.sum

---
Update CLI-Security to 1.13.1

update cli-security to 1.13.1

---

.github/workflows/test.yml

---
The issue is fixed in a fork and will be applied to the repository after merge

Add Mono download to Ubuntu test env

---

testdata/scanrepository/cmd/partial-results-enabled/inner-project/package.json

Fix issue in test

---

go.mod
go.sum

Update dependencies fro release 2.25.0

---

scanrepository/scanrepository.go

Add debug logs to indicate scanned branches in scan-repo

---

go.mod
go.sum
scanpullrequest/scanallpullrequests_test.go
scanrepository/scanrepository_test.go
testdata/scanpullrequest/expectedPullRequestDetailsResponse.json

---
Depends on:
* https://github.com/jfrog/froggit-go/pull/151
Change mocks and add Auther attributes for tests so they will pass and panic will not occur after changes to Froggit-go repo

Add Author attribute for test mocks

---

scanpullrequest/scanpullrequest_test.go
utils/params.go

Allow multiple directories as a value in JF_WORKING_DIR

---

action/lib/utils.js
action/src/utils.ts
action/test/main.spec.ts
buildscripts/getFrogbot.sh
release/buildAndUpload.sh

Remove unsupported darwin/arm architecture

---

.github/workflows/test.yml

Fix for nugget tests in mac and ubuntu

---

utils/params.go

Improve Params fetching conditions

---

go.mod
go.sum

Replace vulnerable version of replace github.com/ulikunitz/xz from version v0.5.14 to v0.5.15
