- commands/scanpullrequest.go
- commands/scanpullrequest_test.go
- go.mod
- go.sum
---
1. Fixes the comparison of 2 scans (source/target) of projects with multi modules  - the comparison is now based on the component Id and not on the order of the elements in the scan results array.
2. The new approach is also suitable for the case when the number of modules has changed between the 2 scans (a new project module has been added in a PR)
3. Fix getNewViolations and getNewVulnerabilities error swallowing.
> Fix Scan Results Comparison for Multi Modules Projects

- commands/createfixpullrequests_test.go
- commands/utils/utils.go
- go.mod
- go.sum
---
-  In case of a scan response without vulnerabilities, send an empty sarif to the Github API. Performing this operation will 'reset' the Github Security Tab and close outdated security alerts.
> Fix - Close outdated alerts on Github Security tab

- docs/install-azure-repos.md
- docs/install-bitbucket-server.md
- docs/install-github.md
- docs/templates/jfrog-pipelines/pipelines-dotnet.yml
- docs/templates/jfrog-pipelines/pipelines-go.yml
- docs/templates/jfrog-pipelines/pipelines-gradle.yml
- docs/templates/jfrog-pipelines/pipelines-maven.yml
- docs/templates/jfrog-pipelines/pipelines-npm.yml
- docs/templates/jfrog-pipelines/pipelines-pip.yml
- docs/templates/jfrog-pipelines/pipelines-pipenv.yml
- docs/templates/jfrog-pipelines/pipelines-poetry.yml
- docs/templates/jfrog-pipelines/pipelines-yarn2.yml
---
The cron frequency in the Frogbot workflow templates is currently 5 minutes, which is way too high. This PR reduces the scan frequency to once an hour.
> Reduce the Scan Repositories cron frequency to one hour

- commands/utils/git.go
---
Extend the default timeout for git-git from its aparent default of 10 seconds to 60 seconds.
> Extend the go-git timeout to 60 seconds

- commands/utils/packagehandlers/mavenpackagehandler.go
---
Fix the following issue, caused by an outdated cache:
> 2023-06-21T03:33:00.748Z [main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.16.0:use-dep-version (default-cli) on project artifactory-monorepo-dev: Version 7.5.1 is not available for artifact org.testng:testng -> [Help 1]
**To reproduce:**
1. Remove all versions above 7.5.0 in the following local files:
* .m2/repository/org/testng/testng/maven-metadata-artifactory-release.xml
* .m2/repository/org/testng/testng/maven-metadata-artifactory-snapshot.xml
* .m2/repository/org/testng/testng/maven-metadata-central.xml
2. Run the following Maven command:
`mvn org.apache.maven.plugins:maven-dependency-plugin:get -Dartifact=org.testng:testng:6.6`
3. Add the `-U` flag to see that the …
> Fix version is not available in Maven

- commands/testdata/config/frogbot-config-empty-scan.yml
- commands/utils/params.go
- commands/utils/params_test.go
---
- If the frogbot-config.yml file does not have the "Projects" field defined, create one with default values.
> Utilize default project when undefined in frogbot-config.yml

- commands/createfixpullrequests.go
- go.mod
- go.sum
---
Update Froggit-go with the bug fix on bitbucket server pull request response containing the entire ref instead of just the branch name
> Fix identification of existing pull request on Bitbucket Server

- .github/workflows/frogbot-scan-and-fix.yml
- commands/testdata/config/frogbot-config-test-unmarshal.yml
- commands/utils/consts.go
- commands/utils/git.go
- commands/utils/params.go
- commands/utils/params_test.go
- docs/install-azure-repos.md
- docs/install-bitbucket-server.md
- docs/install-github.md
- docs/install-gitlab.md
- docs/templates/.frogbot/frogbot-config.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
- docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
- docs/templates/jfrog-pipelines/pipelines-dotnet.yml
- docs/templates/jfrog-pipelines/pipelines-go.yml
- docs/templates/jfrog-pipelines/pipelines-gradle.yml
- docs/templates/jfrog-pipelines/pipelines-maven.yml
- docs/templates/jfrog-pipelines/pipelines-npm.yml
- docs/templates/jfrog-pipelines/pipelines-pip.yml
- docs/templates/jfrog-pipelines/pipelines-pipenv.yml
- docs/templates/jfrog-pipelines/pipelines-poetry.yml
- docs/templates/jfrog-pipelines/pipelines-yarn2.yml
- go.mod
- go.sum
- schema/frogbot-schema.json
---
- The default commit author in Frogbot is `eco-system+frogbot@jfrog.com`, this pull request introduces the abiility to change the commit author with the `JF_GIT_EMAIL_AUTHOR` env or `emailAuthor` field in the frogbot-config file.
> Customize commit email author

- commands/utils/params.go
---
Fix the fallback when can't find frogbot config at the target branch of a pull request.
> Fix extract Frogbot configuration from source branch

- commands/utils/params.go
- commands/utils/params_test.go
- go.sum
---
Bug description:
ScanRepository params validation interfere with ScanPullRequest command while trying to get branches related params.
Fix:
**Env params extraction should behave different depending on command context.**
We assume the context of the command by the pull request ID param. If it is set, we assume we are in ScanPullRequest context, otherwise we are in ScanRepository context.
When in the context of ScanPullRequest, no need to extract branches related env vars.
In the context of ScanRepository, extract branches, git templates and aggregate fixes flag, which are all unrelated to the second context.
> Separate env params extraction by context

- utils/outputwriter/outputwriter.go
- utils/outputwriter/simplifiedoutput.go
- utils/outputwriter/standardoutput.go
> Dont show remediation if not exists

- utils/outputwriter/outputwriter.go
- utils/outputwriter/simplifiedoutput.go
- utils/outputwriter/standardoutput.go
- utils/reviewcomment.go
> Add CVE info to contextual Analysis comment

- utils/params.go
- utils/params_test.go
---
Bug:
When forgetting to set tup JF_GIT_REPO param it resolved in panic call.
Fix:
Enforce mandatory field.
Result:
```
18:20:51 [🔵Info] Frogbot version: 0.0.0
18:20:51 [🚨Error] 'JF_GIT_REPO' environment variable is missing
```
> Enforce  mandatory JF_GIT_REPO param

- scanpullrequest/scanpullrequest_test.go
- scanrepository/scanmultiplerepositories_test.go
- scanrepository/scanrepository_test.go
- utils/params.go
- utils/params_test.go
---
Git Repo param is not mandatory for `scan-and-fix-repos` command
> Fix Multi Repository Scanning

- utils/params.go
> Improve bad API endpoint error hint

- scanrepository/scanrepository.go
- scanrepository/scanrepository_test.go
- utils/consts.go
- utils/git.go
- utils/git_test.go
---
Currently there can be only one aggregated fixes PR open for each repository at all times. 
After the change, which is adding the target branch into the branch name it will allow
for each branch that is being scanned in `scan-repository` branches to have it's own aggregated PR.
- Add base branch to branch name + title ( only aggregate mode )
- This will cause pull requests duplications for existing users.
> Aggregate Fixes per branch

- go.mod
- go.sum
- utils/scandetails.go
---
The transition of all auto-install functions from frogbot to jfrog-cli-core is in progress. Presently, auto-install for NPM is halted, and the install command parameters are forwarded within the process.
Depends on:
https://github.com/jfrog/build-info-go/pull/207
https://github.com/jfrog/jfrog-cli-core/pull/1011
> Blocking NPM auto-install in frogbot + Passing forward install command args

- docs/templates/jfrog-pipelines/pipelines-dotnet.yml
- docs/templates/jfrog-pipelines/pipelines-go.yml
- docs/templates/jfrog-pipelines/pipelines-gradle.yml
- docs/templates/jfrog-pipelines/pipelines-maven.yml
- docs/templates/jfrog-pipelines/pipelines-npm.yml
- docs/templates/jfrog-pipelines/pipelines-pip.yml
- docs/templates/jfrog-pipelines/pipelines-pipenv.yml
- docs/templates/jfrog-pipelines/pipelines-poetry.yml
- docs/templates/jfrog-pipelines/pipelines-yarn2.yml
- schema/frogbot-schema.json
---
Document the change in https://github.com/jfrog/jfrog-cli-core/pull/1022
> Add .git to default exclusions patterns

- schema/schemas_test.go
---
Fix broken tests caused by https://github.com/jfrog/frogbot/pull/568.
* Remove GitHub Actions tests - they moved to here: https://github.com/jfrog/documentation/blob/main/jfrog-applications/frogbot/templates/templates_test.go
* The frogbot-config.yml template has been moved to the `jfrog/documentation` repository. Validate the `frogbot-config.yml` of the `jfrog/frogbot` repository instead.
> Fix Frogbot schema tests

- go.mod
- go.sum
- scanpullrequest/scanpullrequest.go
- scanpullrequest/scanpullrequest_test.go
- scanrepository/scanrepository.go
- utils/utils.go
- utils/utils_test.go
---
* Additionally, a bug has been fixed where on Github issues only one run (last) was displayed as an active issues, while the other was considered resolved.
---
depends on: https://github.com/jfrog/jfrog-cli-core/pull/1030
When `watches` are defined, Show license violations with default location `package-descriptor` at Github security issue tab
> Scan repository - show license violation on Github security issues

- packagehandlers/mavenpackagehandler.go
---
- Add informative errors for the unmarshaling processes in the MavenPackageHandler
- Related to: https://github.com/jfrog/frogbot/issues/587
> Add informative errors for the unmarshaling processes in the MavenPackageHandler

- scanrepository/scanrepository.go
---
Ignoring a typecheck error thrown by linter.
The first argument provided to slice.Contains cannot be inferred as []string type although it is declared correctly in another file
> Fix false positive golangci-linter typecheck error

- scanrepository/scanrepository.go
- utils/utils.go
---
This PR fixes failure in scan-repository (separate PRs for each vulnerability) when there is nothing to push after the fix in some vulnerability (this can happen when there is no fix branch and Frogbot cannot fix the vulnerability)
> Scan fails upon empty PR push

- scanpullrequest/scanallpullrequests.go
- utils/comment.go
---
This PR resolves 2 bugs:
1) In scan-all-pull-requests when we iterate the open PRs and check for each of them if it should be scanned, we used to return upon the first encounter in a PR that should not be scanned. This return got removed since we want to keep iterating the rest of the PRs and check them as well
2) When deleting old comments we used to return if the removal failed. Therefore in this case we don't push the new comments. The removal of old comment is not mandatory and should not prevent the addition of newer comments
> Fix comments removal & scan-all-PRs iteration bugs

- scanrepository/scanrepository.go
- scanrepository/scanrepository_test.go
> Fill xsc version field by calling xscVersion endpoint

- utils/git.go
- utils/git_test.go
---
This PR fixes the issue of printing unmasked URLs in Frogbot's cloning process
> Fix unmasked clone urls in DEBUG prints

- go.mod
- go.sum
- integrationutils.go
- scanpullrequest/scanpullrequest.go
---
Depends on:
* https://github.com/jfrog/jfrog-cli-security/pull/169
> Use sast fingerprint when comparing source and target scan results

- scanrepository/scanrepository.go
- utils/consts.go
- utils/params.go
- utils/params_test.go
---
Enable a new option (`JF_SKIP_AUTOFIX` / `scan.skipAutoFix`) to skip automatic fix at scan repository command.
IF this option is provided, Frogbot will only detect the issues and will not try to fix them
> Add option to skip auto fix in Frogbot scan repository

- azure_test.go
- bitbucket_server_test.go
- github_test.go
- gitlab_test.go
- integrationutils.go
- scanrepository/scanrepository.go
- utils/consts.go
- utils/git.go
- utils/params.go
---
This PR introduces a new ability that enables Frogbot ScanRepository to work with local repository rather than cloning the remote repo within its process.
This enables to manipulate a repo we want to scan from within a CI (prior to Frogbot run) and use the manipulated repo instead of the repo existing in the remote.
For example - If we do not have build for all sub repositories in our remote repo, but we do want to build them in order to scan them (required for the scan and the fix process), we can build our project in the CI, and make Frogbot use the buit repository.
**In order to use this feature we need to set a new env var: JF_USE_LOCAL_REPOSITORY and to navigate to the local repository's root BEFORE frogbot starts its execution**
> Enable using local repository instead cloning a remote repo - ScanRepository

- scanrepository/scanrepository.go
- scanrepository/scanrepository_test.go
- utils/git.go
- utils/testsutils.go
---
This PR improves Frogbot's ability to detect new locally created files, and remove them before pushing the fixes PRs.
This improvement allows Frogbot to push cleaner PRs ,with changes ONLY in the already existing files and not pushing newly created files (like new lock files, node_modules etc...)
> Clear new locally created files before pushing a fix

- scanpullrequest/scanpullrequest.go
- scanrepository/scanrepository.go
- utils/consts.go
- utils/params.go
- utils/params_test.go
- utils/scandetails.go
---
Add option in config (`disableJas`)/ env var (`JF_DISABLE_ADVANCED_SECURITY`) to disable JAS scans
> Add option to disable Jas scans

- testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_simplified.md
- testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_standard.md
- testdata/messages/reviewcomment/secrets/secret_review_content_simplified.md
- testdata/messages/reviewcomment/secrets/secret_review_content_standard.md
- utils/comment.go
- utils/comment_test.go
- utils/consts.go
- utils/outputwriter/outputcontent.go
- utils/outputwriter/outputcontent_test.go
- utils/params.go
---
Add an option to generate secrets comments in scan PR using `JF_PR_SHOW_SECRETS_COMMENTS=true`
> Show secrets detected at PR scan

- utils/consts.go
- utils/params.go
- utils/scandetails.go
---
You can now pass `JF_PNPM_MAX_TREE_DEPTH` to control the max depth of the Pnpm dependency tree generated.
> Add option to control the Pnpm dependencies tree depth

- scanpullrequest/scanpullrequest.go
---
When scan fails or issue occur, `projectIssues *issues.ScansIssuesCollection` can sometime be `nil` that caused `PANIC`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf77e89]
goroutine 1 [running]:
github.com/jfrog/frogbot/v2/scanpullrequest.auditPullRequest(0xc0003db208, {0x1580e40, 0xc0003a8ba0})
/var/opt/jfrog/pipelines/data/release_frogbot/runs/4285355/steps/Release/31033311/dependencyState/resources/frogbotGit/scanpullrequest/scanpullrequest.go:167 +0x4e9
github.com/jfrog/frogbot/v2/scanpullrequest.scanPullRequest(0xc0003db208, {0x1580e40, 0xc0003a8ba0})
/var/opt/jfrog/pipelines/data/release_frogbot/runs/4285355/steps/Release/31033311/dependencyState/resources/frogbotGit/scanpullrequest/sca …
```
> Don't access ScanStatus on nil

- .github/workflows/oidc-test.yml
---
Due to security enhancement to the OIDC mechanism, identity mappings require more strict fields that will limit the oidc mechanism to a certain flow/owner/repository etc..
Since we want the tests to work in jfrog/frogbot as well as personal forks (in order to reflect changes before merges) we cannot add those kind of fields. Therefore we added a field that allows to use the "lighter" kind of identity mappings like we had before the change. Since this affects only the OIDC test we have no security risk.
We cannot see any CI changes before we merge it, therefore the tests are still seems to be failing here, but in a fork we can see the issue is fixed:
> Fix OIDC broken test

- utils/outputwriter/outputcontent_test.go
- utils/outputwriter/outputwriter.go
---
Try to fix the following issue:
```
12:03:58 [Error] pull request #35 scan in the 'test' repository returned the following error:
couldn't add pull request comment: Status: 400 Bad Request, Body: {"errors":[{"context":"text","message":"Please enter a non-empty value less than 32768 characters","exceptionName":null}]}
```
> Make sure no attempts to create empty comment for PR Scan on split
